Repository pokhengly/onlineBankFrontend, pull requests merged in 2023-10, with the labels that each got.

#4 test
  index.html
Labels: enhancement

#5 add code in dashboard.html and dashboard.css
  .idea/inspectionProfiles/Project_Default.xml
  dashboard.html
  public/assets/cssDemo/dashboard.css
Labels: enhancement

#6 test
  dashboard.html
Labels: enhancement

#7 jghjgh
  dashboard.html
Labels: enhancement

#11 tesr
  dashboard.html
Labels: good first issue

#13 jh
  index.html
Labels: bug

#15 Done file index.html index.css with register.html register.css
  public/assets/css/default.css
  public/assets/cssDemo/index.css
  public/assets/cssDemo/register.css
  register.html
Labels: enhancement

#17 reviewed
  dashboard.html
  email.html
  index.html
  login.html
  public/assets/cssDemo/dashboard.css
  public/assets/cssDemo/index.css
  public/assets/cssDemo/register.css
  register.html
Labels: bug

#19 test
  components/offcanvas.html
  dashboard.html
  public/assets/cssDemo/dashboard.css
Labels: bug

#20 test
  dashboard.html
Labels: enhancement

#21 tested
  dashboard.html
Labels: enhancement

#22 new login
  login.html
  public/assets/cssDemo/login.css
Labels: invalid

#23 work on dashboard.html and dashboard.css and main.js
  components/accordian.html
  components/offcanvas.html
  components/popovers.html
  components/toast.html
  dashboard.html
  public/assets/cssDemo/dashboard.css
  public/assets/images/offcanvas_bg.jpg
  public/assets/js/main.js
Labels: enhancement

#24 file email.hmtl and email.css
  email.html
  public/assets/css/email.css
Labels: documentation

#25 review email.html and email.css
  dashboard.html
  email.html
  public/assets/cssDemo/dashboard.css
  public/assets/cssDemo/email.css
  public/assets/js/main.js
Labels: bug

#30 Done for everthing on frontend
  .idea/inspectionProfiles/Project_Default.xml
  dashboard.html
  email.html
  index.html
  login.html
  public/assets/cssDemo/dashboard.css
  public/assets/cssDemo/email.css
  register.html
Labels: bug

#31 Done email.html and email.css
  .idea/git_toolbox_prj.xml
  .idea/inspectionProfiles/Project_Default.xml
  error.html
  public/assets/cssDemo/error.css
Labels: enhancement

#32 Done on frontend
  .idea/inspectionProfiles/Project_Default.xml
  email.html
  public/assets/cssDemo/dashboard.css
  public/assets/cssDemo/email.css
  public/assets/cssDemo/error.css
Labels: enhancement
